"""add timestamp to api key

Revision ID: d903e6b7f67d
Revises: 818d75d1e6a1
Create Date: 2024-02-23 17:19:19.378399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd903e6b7f67d'
down_revision: Union[str, None] = '818d75d1e6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'created_at')
    # ### end Alembic commands ###
